# Setup
title:               Cain Hill
tagline:             ''
description:         ''
url:                 https://cainhill.github.io
baseurl:             ''
paginate:            5
permalink:           /:title/ # How should URLs be formed?

# Which folders have post content?
collections:
  blog:
    output: true
    permalink: /blog/:title/
  off-topic:
    output: true
    permalink: /off-topic/:title/
  direct:
    output: true
    permalink: /direct/:title/

# Which layout type should each URL use?		
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
  - scope:
      path: "_blog"
    values:
      layout: post
  - scope:
      path: "_off-topic"
    values:
      layout: post
  - scope:
      path: "_direct"
    values:
      layout: post

# About/contact
author:
  name:              Cain Hill
  url:               ''
  email:             ''

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
