# Setup
title:               Cain Hill
tagline:             ''
description:         ''
url:                 https://cainhill.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Cain Hill
  url:               ''
  email:             ''

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
